language: c

# Jun 28, 2020 - 9711fc017be7614a96ebe3759d779ab7de59bb96 - build #3 <-- weird change


matrix:
  include:
    - os: linux
      dist: trusty
      env:
       - SIMH_CHECKOUT=166852935d9abba4f06e85cdacd97a51027c0877
       - OENV="Linux trusty"

    - os: linux
      dist: bionic
      env:
       - SIMH_CHECKOUT=166852935d9abba4f06e85cdacd97a51027c0877
       - OENV="Linux bionic"
       
    - os: osx
      osx_image: xcode12
      env:
       - SIMH_CHECKOUT=166852935d9abba4f06e85cdacd97a51027c0877
       - OENV="macOS 10.15.5 - xcode12.0"
       
script: 
   - ./script try "${SIMH_CHECKOUT}"
