language: c

matrix:
  include:
    - os: linux
      dist: trusty
      env:
       - SIMH_CHECKOUT=9711fc017be7614a96ebe3759d779ab7de59bb96
       - OENV="Linux trusty"

    - os: linux
      dist: bionic
      env:
       - SIMH_CHECKOUT=9711fc017be7614a96ebe3759d779ab7de59bb96
       - OENV="Linux bionic"
       
script: 
   - ./script try "${SIMH_CHECKOUT}"
