language: c

# Jun 28, 2020 - 9711fc017be7614a96ebe3759d779ab7de59bb96 - build #3 <-- weird change


matrix:
  include:
    - os: linux
      dist: trusty
      env:
       - SIMH_CHECKOUT=331f6897470d9a53508ad42db2d27f76ec6ddf4d
       - OENV="Linux trusty"

    - os: linux
      dist: bionic
      env:
       - SIMH_CHECKOUT=331f6897470d9a53508ad42db2d27f76ec6ddf4d
       - OENV="Linux bionic"
       
    - os: osx
      osx_image: xcode12
      env:
       - SIMH_CHECKOUT=331f6897470d9a53508ad42db2d27f76ec6ddf4d
       - OENV="macOS 10.15.5 - xcode12.0"
       
script: 
   - ./script try "${SIMH_CHECKOUT}"
