language: c

# Jun 28, 2020 - 9711fc017be7614a96ebe3759d779ab7de59bb96 - build #3
# May 24, 2020 - 6a816001ef0f5da9ef29ea7819cf6744c4711a73 - build #4

matrix:
  include:
    - os: linux
      dist: trusty
      env:
       - SIMH_CHECKOUT=6a816001ef0f5da9ef29ea7819cf6744c4711a73
       - OENV="Linux trusty"

    - os: linux
      dist: bionic
      env:
       - SIMH_CHECKOUT=6a816001ef0f5da9ef29ea7819cf6744c4711a73
       - OENV="Linux bionic"
       
script: 
   - ./script try "${SIMH_CHECKOUT}"
