#!/bin/bash

buildsimh() {
  git clone https://github.com/simh/simh.git
  cd simh
  git checkout $1
  gmake vax || make vax
  cd ..
}

rebuildsimh() {
  cd simh
  gmake clean || make clean
  git checkout $1
  gmake vax || make vax
  cd ..
}

writeinis() {
  cat >microvax3900.ini <<__EOF__
SET RUNLIMIT 25 seconds
SET ROM DELAY
ATT NVR nvram.dat
DEP BDR 1
EXPECT "Device\? \x5BXQA0\x5D: "  SEND "dua0:\r" ;GO
BOOT CPU
QUIT
__EOF__

  cat >sv.ini<<__EOF__
SHOW VERSION
QUIT
__EOF__
}

runit() {
simh/BIN/microvax3900 sv.ini
for c in 1 2 3 4 5 ; do
  echo; echo ++++++++++ run $c $(date) ++++++++++
  rm -f nvram.dat
  simh/BIN/microvax3900
  echo; echo ++++++++++++++++++++++++++++++++++++
done
}

main() {
buildsimh $1
writeinis
runit
for commit in $(cd simh; git log|grep "^commit "|sed -e 1d|head -50|awk '{print $2}'; cd ..); do
  echo XXXXXXXXXXXXXXXXXX now at commit ${commit} XXXXXXXXXXXXXXXXXX 
  rebuildsimh "${commit}"
  runit
done
}

((${#}-2))&&$1
((${#}-1))&&main $2
